FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
RUN corepack enable \
    && yarn config set registry https://registry.npmjs.org \
    && yarn install --frozen-lockfile --network-timeout 600000

COPY . .

EXPOSE 3000

CMD ["sh", "-lc", "corepack enable && yarn dev --hostname 0.0.0.0 --port 3000"]
